// 客户端主动请求与对应响应（C/S 契约的客户端上行部分）。
//
// 这个文件是 gate 转发白名单的**唯一来源**：gate 只转发这里定义过的 route
// （见 joltgo/gate/routes.go 的 allowedRoutes）。服务端主动推送不在这里 ——
// 它们按发送方归到 match/protos/match.proto 与 game/protos/game.proto。
//
// 线上 route 一律三段式 `server.service.method`（pitaya 的路由格式）：
//   - 客户端 → gate → account：account.account.register / account.account.login /
//     account.account.resume（Request/Response，不是 Notify/Push —— 见 docs/API.md）
//   - 客户端 → gate → logic：logic.logic.state / logic.logic.purchase /
//     logic.logic.equip / logic.logic.profile（Request/Response）
//   - 客户端 → gate → match：match.match.join（Notify）/ match.match.pending /
//     match.match.abandon / match.match.cancel（Request/Response —— pending 是进大厅时
//     问「我有没有没打完的局」，abandon 是放弃那场对局，放弃只把该玩家从实例里释放出来、
//     实例照常打完）
//   - 客户端 → gate → game：game.game.cmd（Notify）/ game.game.resync（Notify，空 payload）
//
// 注：gate.sys.kick 用的是 pitaya 内置的 KickMsg / KickAnswer
// （third_party/pitaya/pkg/protos），不在本文件定义范围内 —— 它同样走 C/S 通道，
// 只是方向是服务端 → 客户端。
//
// 序列化用 pitaya 的 protobuf serializer。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: gate/protos/gate.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterMsg 是注册请求。用户名 3-16 位 [a-zA-Z0-9_]，密码 6-64 位。
type RegisterMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginMsg 是登录请求。
type LoginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginMsg) Reset() {
	*x = LoginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMsg) ProtoMessage() {}

func (x *LoginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMsg.ProtoReflect.Descriptor instead.
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{1}
}

func (x *LoginMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ResumeMsg 是凭证恢复请求：客户端持有 token，换回会话。
type ResumeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResumeMsg) Reset() {
	*x = ResumeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeMsg) ProtoMessage() {}

func (x *ResumeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeMsg.ProtoReflect.Descriptor instead.
func (*ResumeMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginReply 是 register / login / resume 的统一应答，客户端用同一段代码处理。
// ok=false 时 reason 是机器可读的原因码（bad_credentials / name_taken /
// bad_username / bad_password / rate_limited / token_invalid / internal）。
type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                          // ok=true 时有效
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                    // 保留用户输入的原始大小写，供 UI 显示
	AccountId string `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 十进制字符串，仅供诊断
	Reason    string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                        // ok=false 时的原因码
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReply) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogicStateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicStateMsg) Reset() {
	*x = LogicStateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicStateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicStateMsg) ProtoMessage() {}

func (x *LogicStateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicStateMsg.ProtoReflect.Descriptor instead.
func (*LogicStateMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{4}
}

type PurchaseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *PurchaseMsg) Reset() {
	*x = PurchaseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseMsg) ProtoMessage() {}

func (x *PurchaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseMsg.ProtoReflect.Descriptor instead.
func (*PurchaseMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseMsg) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PurchaseMsg) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type EquipMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *EquipMsg) Reset() {
	*x = EquipMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipMsg) ProtoMessage() {}

func (x *EquipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipMsg.ProtoReflect.Descriptor instead.
func (*EquipMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{6}
}

func (x *EquipMsg) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type LogicShopItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId        string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Price         int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	EquipSlot     string `protobuf:"bytes,4,opt,name=equip_slot,json=equipSlot,proto3" json:"equip_slot,omitempty"`
	OwnedQuantity int64  `protobuf:"varint,5,opt,name=owned_quantity,json=ownedQuantity,proto3" json:"owned_quantity,omitempty"`
}

func (x *LogicShopItem) Reset() {
	*x = LogicShopItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicShopItem) ProtoMessage() {}

func (x *LogicShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicShopItem.ProtoReflect.Descriptor instead.
func (*LogicShopItem) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{7}
}

func (x *LogicShopItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LogicShopItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LogicShopItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LogicShopItem) GetEquipSlot() string {
	if x != nil {
		return x.EquipSlot
	}
	return ""
}

func (x *LogicShopItem) GetOwnedQuantity() int64 {
	if x != nil {
		return x.OwnedQuantity
	}
	return 0
}

type LogicStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                    bool             `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason                string           `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Coins                 int64            `protobuf:"varint,3,opt,name=coins,proto3" json:"coins,omitempty"`
	Items                 []*LogicShopItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	EquippedPrimaryWeapon string           `protobuf:"bytes,5,opt,name=equipped_primary_weapon,json=equippedPrimaryWeapon,proto3" json:"equipped_primary_weapon,omitempty"`
}

func (x *LogicStateReply) Reset() {
	*x = LogicStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicStateReply) ProtoMessage() {}

func (x *LogicStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicStateReply.ProtoReflect.Descriptor instead.
func (*LogicStateReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{8}
}

func (x *LogicStateReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LogicStateReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LogicStateReply) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *LogicStateReply) GetItems() []*LogicShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LogicStateReply) GetEquippedPrimaryWeapon() string {
	if x != nil {
		return x.EquippedPrimaryWeapon
	}
	return ""
}

// 历史里的单场战绩（下发结构，与持久化结构分开）。
type MatchRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId         string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Won             bool   `protobuf:"varint,2,opt,name=won,proto3" json:"won,omitempty"`
	Kills           int32  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths          int32  `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	OpponentKills   int32  `protobuf:"varint,5,opt,name=opponent_kills,json=opponentKills,proto3" json:"opponent_kills,omitempty"`
	DurationSeconds int32  `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	OpponentName    string `protobuf:"bytes,7,opt,name=opponent_name,json=opponentName,proto3" json:"opponent_name,omitempty"`
	EndedAt         int64  `protobuf:"varint,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
}

func (x *MatchRecord) Reset() {
	*x = MatchRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRecord) ProtoMessage() {}

func (x *MatchRecord) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRecord.ProtoReflect.Descriptor instead.
func (*MatchRecord) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{9}
}

func (x *MatchRecord) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchRecord) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *MatchRecord) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *MatchRecord) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *MatchRecord) GetOpponentKills() int32 {
	if x != nil {
		return x.OpponentKills
	}
	return 0
}

func (x *MatchRecord) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *MatchRecord) GetOpponentName() string {
	if x != nil {
		return x.OpponentName
	}
	return ""
}

func (x *MatchRecord) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type PlayerProfileMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayerProfileMsg) Reset() {
	*x = PlayerProfileMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfileMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileMsg) ProtoMessage() {}

func (x *PlayerProfileMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileMsg.ProtoReflect.Descriptor instead.
func (*PlayerProfileMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{10}
}

type PlayerProfileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok             bool           `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason         string         `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Level          int32          `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Xp             int64          `protobuf:"varint,4,opt,name=xp,proto3" json:"xp,omitempty"`
	XpIntoLevel    int64          `protobuf:"varint,5,opt,name=xp_into_level,json=xpIntoLevel,proto3" json:"xp_into_level,omitempty"`
	XpForNextLevel int64          `protobuf:"varint,6,opt,name=xp_for_next_level,json=xpForNextLevel,proto3" json:"xp_for_next_level,omitempty"`
	Kills          int32          `protobuf:"varint,7,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths         int32          `protobuf:"varint,8,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Matches        int32          `protobuf:"varint,9,opt,name=matches,proto3" json:"matches,omitempty"`
	Wins           int32          `protobuf:"varint,10,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses         int32          `protobuf:"varint,11,opt,name=losses,proto3" json:"losses,omitempty"`
	RecentMatches  []*MatchRecord `protobuf:"bytes,12,rep,name=recent_matches,json=recentMatches,proto3" json:"recent_matches,omitempty"`
}

func (x *PlayerProfileReply) Reset() {
	*x = PlayerProfileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileReply) ProtoMessage() {}

func (x *PlayerProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileReply.ProtoReflect.Descriptor instead.
func (*PlayerProfileReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerProfileReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PlayerProfileReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PlayerProfileReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProfileReply) GetXp() int64 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *PlayerProfileReply) GetXpIntoLevel() int64 {
	if x != nil {
		return x.XpIntoLevel
	}
	return 0
}

func (x *PlayerProfileReply) GetXpForNextLevel() int64 {
	if x != nil {
		return x.XpForNextLevel
	}
	return 0
}

func (x *PlayerProfileReply) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerProfileReply) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerProfileReply) GetMatches() int32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *PlayerProfileReply) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *PlayerProfileReply) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *PlayerProfileReply) GetRecentMatches() []*MatchRecord {
	if x != nil {
		return x.RecentMatches
	}
	return nil
}

// JoinMsg 是加入匹配的请求。身份来自会话绑定（account 服务在登录时做的），
// 这里不再携带任何凭证 —— 字段清空后 route 与 handler 签名都不变。
type JoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinMsg) Reset() {
	*x = JoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMsg) ProtoMessage() {}

func (x *JoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMsg.ProtoReflect.Descriptor instead.
func (*JoinMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{12}
}

// PendingMatchMsg 是「我有没有没打完的局」的查询请求（route "match.match.pending"）。
// 客户端登录成功、刚进大厅时问一次：命中就弹「回到对局 / 放弃对局」的询问框。
// 身份来自会话，payload 为空。
type PendingMatchMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PendingMatchMsg) Reset() {
	*x = PendingMatchMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMatchMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMatchMsg) ProtoMessage() {}

func (x *PendingMatchMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMatchMsg.ProtoReflect.Descriptor instead.
func (*PendingMatchMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{13}
}

// PendingMatchReply 是 match.match.pending 的应答。
// found=false 时 match_id 无意义（空串）。
type PendingMatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found   bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	MatchId string `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
}

func (x *PendingMatchReply) Reset() {
	*x = PendingMatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMatchReply) ProtoMessage() {}

func (x *PendingMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMatchReply.ProtoReflect.Descriptor instead.
func (*PendingMatchReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{14}
}

func (x *PendingMatchReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PendingMatchReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

// AbandonMatchMsg 是「放弃那场没打完的局」的请求（route "match.match.abandon"）。
// 语义：**只把当前玩家从对局里释放出来**（不再收帧、不再参与结算），对局实例本身
// 照常推进 —— 对手还在打，他的那一局不因为有人放弃而中断。身份来自会话。
type AbandonMatchMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbandonMatchMsg) Reset() {
	*x = AbandonMatchMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonMatchMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonMatchMsg) ProtoMessage() {}

func (x *AbandonMatchMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonMatchMsg.ProtoReflect.Descriptor instead.
func (*AbandonMatchMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{15}
}

// AbandonMatchReply 是 match.match.abandon 的应答。
// reason：released | not_found | unauthenticated | internal。
type AbandonMatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AbandonMatchReply) Reset() {
	*x = AbandonMatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonMatchReply) ProtoMessage() {}

func (x *AbandonMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonMatchReply.ProtoReflect.Descriptor instead.
func (*AbandonMatchReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{16}
}

func (x *AbandonMatchReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AbandonMatchReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MatchCancelMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchCancelMsg) Reset() {
	*x = MatchCancelMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCancelMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelMsg) ProtoMessage() {}

func (x *MatchCancelMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelMsg.ProtoReflect.Descriptor instead.
func (*MatchCancelMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{17}
}

type MatchCancelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // cancelled | already_matched | not_queued | unauthenticated
}

func (x *MatchCancelReply) Reset() {
	*x = MatchCancelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCancelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelReply) ProtoMessage() {}

func (x *MatchCancelReply) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelReply.ProtoReflect.Descriptor instead.
func (*MatchCancelReply) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{18}
}

func (x *MatchCancelReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MatchCancelReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CommandMsg 是一帧的上行命令：把输入与射击合并成一条消息发送（帧是最小发送单位）。
// shoot 是边沿触发，未触发时为 false。
type CommandMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move   []float32 `protobuf:"fixed32,1,rep,packed,name=move,proto3" json:"move,omitempty"`     // [wx, wz]，世界空间水平期望速度（m/s）
	Yaw    float32   `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`              // 水平朝向（弧度，绕 Y 轴）
	Jump   bool      `protobuf:"varint,3,opt,name=jump,proto3" json:"jump,omitempty"`             // 跳跃边沿触发（服务端下一 tick 消费）
	Shoot  bool      `protobuf:"varint,4,opt,name=shoot,proto3" json:"shoot,omitempty"`           // 射击边沿触发
	Origin []float32 `protobuf:"fixed32,5,rep,packed,name=origin,proto3" json:"origin,omitempty"` // [x, y, z] 枪口位置（shoot 为 true 时有效）
	Dir    []float32 `protobuf:"fixed32,6,rep,packed,name=dir,proto3" json:"dir,omitempty"`       // [x, y, z] 射击方向（服务端会归一化）
}

func (x *CommandMsg) Reset() {
	*x = CommandMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gate_protos_gate_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMsg) ProtoMessage() {}

func (x *CommandMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gate_protos_gate_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMsg.ProtoReflect.Descriptor instead.
func (*CommandMsg) Descriptor() ([]byte, []int) {
	return file_gate_protos_gate_proto_rawDescGZIP(), []int{19}
}

func (x *CommandMsg) GetMove() []float32 {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *CommandMsg) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *CommandMsg) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *CommandMsg) GetShoot() bool {
	if x != nil {
		return x.Shoot
	}
	return false
}

func (x *CommandMsg) GetOrigin() []float32 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CommandMsg) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

var File_gate_protos_gate_proto protoreflect.FileDescriptor

var file_gate_protos_gate_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x74, 0x65, 0x22, 0x45,
	0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x42, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x73,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x85, 0x01, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x42, 0x0a, 0x0b, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x08, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0xa7,
	0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6c, 0x6f,
	0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x64,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xb2, 0x01, 0x0a, 0x0f, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65,
	0x64, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64,
	0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x22, 0xfa, 0x01,
	0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x77, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x74, 0x68, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x64, 0x65, 0x61, 0x74, 0x68, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6c, 0x6c, 0x73, 0x12,
	0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x22, 0xdf,
	0x02, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x78, 0x70, 0x12, 0x22, 0x0a, 0x0d, 0x78, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x6f, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x78, 0x70, 0x49, 0x6e,
	0x74, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x29, 0x0a, 0x11, 0x78, 0x70, 0x5f, 0x66, 0x6f,
	0x72, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x78, 0x70, 0x46, 0x6f, 0x72, 0x4e, 0x65, 0x78, 0x74, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65, 0x61, 0x74, 0x68, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69,
	0x6e, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x6f, 0x73, 0x73, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6c, 0x6f, 0x73, 0x73, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x22, 0x09, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x22, 0x44,
	0x0a, 0x11, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x22, 0x3b, 0x0a, 0x11, 0x41, 0x62, 0x61, 0x6e, 0x64,
	0x6f, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x68, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x6f,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x4a, 0x04, 0x08, 0x07, 0x10,
	0x08, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x6a, 0x6f, 0x6c, 0x74,
	0x67, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gate_protos_gate_proto_rawDescOnce sync.Once
	file_gate_protos_gate_proto_rawDescData = file_gate_protos_gate_proto_rawDesc
)

func file_gate_protos_gate_proto_rawDescGZIP() []byte {
	file_gate_protos_gate_proto_rawDescOnce.Do(func() {
		file_gate_protos_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_gate_protos_gate_proto_rawDescData)
	})
	return file_gate_protos_gate_proto_rawDescData
}

var file_gate_protos_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_gate_protos_gate_proto_goTypes = []any{
	(*RegisterMsg)(nil),        // 0: gate.RegisterMsg
	(*LoginMsg)(nil),           // 1: gate.LoginMsg
	(*ResumeMsg)(nil),          // 2: gate.ResumeMsg
	(*LoginReply)(nil),         // 3: gate.LoginReply
	(*LogicStateMsg)(nil),      // 4: gate.LogicStateMsg
	(*PurchaseMsg)(nil),        // 5: gate.PurchaseMsg
	(*EquipMsg)(nil),           // 6: gate.EquipMsg
	(*LogicShopItem)(nil),      // 7: gate.LogicShopItem
	(*LogicStateReply)(nil),    // 8: gate.LogicStateReply
	(*MatchRecord)(nil),        // 9: gate.MatchRecord
	(*PlayerProfileMsg)(nil),   // 10: gate.PlayerProfileMsg
	(*PlayerProfileReply)(nil), // 11: gate.PlayerProfileReply
	(*JoinMsg)(nil),            // 12: gate.JoinMsg
	(*PendingMatchMsg)(nil),    // 13: gate.PendingMatchMsg
	(*PendingMatchReply)(nil),  // 14: gate.PendingMatchReply
	(*AbandonMatchMsg)(nil),    // 15: gate.AbandonMatchMsg
	(*AbandonMatchReply)(nil),  // 16: gate.AbandonMatchReply
	(*MatchCancelMsg)(nil),     // 17: gate.MatchCancelMsg
	(*MatchCancelReply)(nil),   // 18: gate.MatchCancelReply
	(*CommandMsg)(nil),         // 19: gate.CommandMsg
}
var file_gate_protos_gate_proto_depIdxs = []int32{
	7, // 0: gate.LogicStateReply.items:type_name -> gate.LogicShopItem
	9, // 1: gate.PlayerProfileReply.recent_matches:type_name -> gate.MatchRecord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gate_protos_gate_proto_init() }
func file_gate_protos_gate_proto_init() {
	if File_gate_protos_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gate_protos_gate_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LogicStateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PurchaseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EquipMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LogicShopItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LogicStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*MatchRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerProfileMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerProfileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*JoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*PendingMatchMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*PendingMatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AbandonMatchMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AbandonMatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*MatchCancelMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*MatchCancelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gate_protos_gate_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*CommandMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gate_protos_gate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_protos_gate_proto_goTypes,
		DependencyIndexes: file_gate_protos_gate_proto_depIdxs,
		MessageInfos:      file_gate_protos_gate_proto_msgTypes,
	}.Build()
	File_gate_protos_gate_proto = out.File
	file_gate_protos_gate_proto_rawDesc = nil
	file_gate_protos_gate_proto_goTypes = nil
	file_gate_protos_gate_proto_depIdxs = nil
}
