// game 的协议定义：game 推给客户端的消息 + 服务内部消息。
//
// 归属规则（与 gate/protos/gate.proto、match/protos/match.proto 一致，三份文件
// 之间**没有 import 关系**）：
//   - 客户端主动请求 → gate/protos/gate.proto
//   - match 推给客户端的 → match/protos/match.proto
//   - game 推给客户端的、以及服务之间的内部消息 → 本文件
//
// 内部消息留在这里是因为它们的双方（game ↔ logic / gate、gm → game）不涉及客户端；
// 其中 SlotResult 同时被下发的 MatchEnded 与上报的 RecordMatchMsg 使用，两个消息
// 都在本文件，所以零 import。
//
// 内部 RPC 的 route 一览（都是三段式，用 RegisterRemote 注册）：
//   - match → game：game.game.create（CreateGameMsg）/ game.game.rejoin（RejoinMsg）
//     / game.game.leave（LeaveMsg，放弃对局时把玩家从实例里摘出来）
//   - match → gate：gate.gate.bindgame（BindGameMsg）
//   - game → logic：logic.logic.recordmatch（RecordMatchMsg，战绩上报）
//   - account → logic：logic.logic.online（UserOnlineMsg）
//   - gm → match：match.match.addbots（AddBotsMsg）
//   - gm → logic：logic.logic.grantcoins（GrantCoinsMsg）
//
// 这些 route 客户端**发不到**：gate 只转发 gate/protos/gate.proto 里定义过的 route
// （见 joltgo/gate/routes.go 的 allowedRoutes）。
//
// 同步不走手写快照，走通用「实体-属性」增量：属性表（Schema）在 full 帧里下发一次，
// 之后所有帧都是 (实体, 属性, 终值) 的 op。新增属性不需要改动本文件的字段定义。
//
// 序列化用 pitaya 的 protobuf serializer。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: game/protos/game.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaField 是一个同步属性的声明。
type SchemaField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 属性 ID（Frame 里的 AttrValue.id）
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 属性名，客户端按名字取值
	Kind int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"` // 值类型，与 replication.Kind 取值一致
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaField) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// Schema 是属性表，随 full 帧下发。
type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields  []*SchemaField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Version uint32         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 属性表哈希，客户端据此检测前后端不一致
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// AttrValue 是一个属性的取值。按 schema 声明的 kind 取用其中一个字段。
type AttrValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	F  []float32 `protobuf:"fixed32,2,rep,packed,name=f,proto3" json:"f,omitempty"` // KindF32(1 项) / KindVec2(2) / KindVec3(3) / KindVec4(4)
	I  int32     `protobuf:"varint,3,opt,name=i,proto3" json:"i,omitempty"`         // KindI32
	B  bool      `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`         // KindBool
	S  string    `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"`          // KindStr
}

func (x *AttrValue) Reset() {
	*x = AttrValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrValue) ProtoMessage() {}

func (x *AttrValue) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrValue.ProtoReflect.Descriptor instead.
func (*AttrValue) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{2}
}

func (x *AttrValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrValue) GetF() []float32 {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *AttrValue) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *AttrValue) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *AttrValue) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// EntityDelta 是一个实体在本帧的变化。应用顺序：destroy → removed → set。
type EntityDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Destroy bool         `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"`
	Removed []uint32     `protobuf:"varint,3,rep,packed,name=removed,proto3" json:"removed,omitempty"`
	Set     []*AttrValue `protobuf:"bytes,4,rep,name=set,proto3" json:"set,omitempty"`
}

func (x *EntityDelta) Reset() {
	*x = EntityDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDelta) ProtoMessage() {}

func (x *EntityDelta) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDelta.ProtoReflect.Descriptor instead.
func (*EntityDelta) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{3}
}

func (x *EntityDelta) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDelta) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *EntityDelta) GetRemoved() []uint32 {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *EntityDelta) GetSet() []*AttrValue {
	if x != nil {
		return x.Set
	}
	return nil
}

// Frame 是一帧同步消息。full=true 表示全量帧（重连 / 首次进入），客户端应先
// 清空本地状态再整体覆盖；此时 schema 一并携带。
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step     int32          `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"` // 帧号（= 服务端 tick 计数）
	Full     bool           `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	Entities []*EntityDelta `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	Schema   *Schema        `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{4}
}

func (x *Frame) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Frame) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *Frame) GetEntities() []*EntityDelta {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Frame) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// 单个槽位的结算数据。下标即 player_idx；uid 为空串表示该槽位没有真实玩家。
type SlotResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Kills  int32  `protobuf:"varint,2,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths int32  `protobuf:"varint,3,opt,name=deaths,proto3" json:"deaths,omitempty"`
	// left = true：该槽位的玩家中途放弃了对局（uid 仍然是他的账号 ID）。
	// 结算方据此把这一位**排除在结算之外**（不计战绩、不推结算），而对局本身仍然
	// 是「两个人的局」—— 这正是「放弃 ≠ 没有对手」的区分点：
	// uid=="" 且 left=false 才是「这个槽位压根没人」，那种局不入账。
	Left bool `protobuf:"varint,4,opt,name=left,proto3" json:"left,omitempty"`
}

func (x *SlotResult) Reset() {
	*x = SlotResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotResult) ProtoMessage() {}

func (x *SlotResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotResult.ProtoReflect.Descriptor instead.
func (*SlotResult) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{5}
}

func (x *SlotResult) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SlotResult) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *SlotResult) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *SlotResult) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

// onMatchEnded 推送载荷：一局结束的权威信号。
type MatchEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId         string        `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerSlot      int32         `protobuf:"varint,2,opt,name=winner_slot,json=winnerSlot,proto3" json:"winner_slot,omitempty"`
	Slots           []*SlotResult `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	DurationSeconds int32         `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
}

func (x *MatchEnded) Reset() {
	*x = MatchEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnded) ProtoMessage() {}

func (x *MatchEnded) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnded.ProtoReflect.Descriptor instead.
func (*MatchEnded) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{6}
}

func (x *MatchEnded) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchEnded) GetWinnerSlot() int32 {
	if x != nil {
		return x.WinnerSlot
	}
	return 0
}

func (x *MatchEnded) GetSlots() []*SlotResult {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *MatchEnded) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// BindGameMsg 是 match → gate 的 RPC 请求（route "gate.gate.bindgame"）：请玩家
// 所属的 gate 把对局归属写进它自己的会话数据（gate 据 gameServerId 定点路由
// game.*）。game_server_id 为空表示回滚（清掉归属）。
type BindGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameServerId string `protobuf:"bytes,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MatchId      string `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIdx    int32  `protobuf:"varint,4,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"`
}

func (x *BindGameMsg) Reset() {
	*x = BindGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGameMsg) ProtoMessage() {}

func (x *BindGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGameMsg.ProtoReflect.Descriptor instead.
func (*BindGameMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{7}
}

func (x *BindGameMsg) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BindGameMsg) GetGameServerId() string {
	if x != nil {
		return x.GameServerId
	}
	return ""
}

func (x *BindGameMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *BindGameMsg) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// BindGameReply 是 gate.gate.bindgame 的应答。found=false 表示该 gate 上没有
// 这个会话（玩家已掉线）。
type BindGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *BindGameReply) Reset() {
	*x = BindGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGameReply) ProtoMessage() {}

func (x *BindGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGameReply.ProtoReflect.Descriptor instead.
func (*BindGameReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{8}
}

func (x *BindGameReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// CreateGameMsg 是 match → game 创建对局的 RPC 请求（route "game.create"）。
// uids 按槽位顺序（下标即 player_idx），1 个 = 单人兜底局。
type CreateGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string   `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Uids    []string `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *CreateGameMsg) Reset() {
	*x = CreateGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameMsg) ProtoMessage() {}

func (x *CreateGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameMsg.ProtoReflect.Descriptor instead.
func (*CreateGameMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGameMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateGameMsg) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

// CreateGameReply 是 game.create 的 RPC 应答（0 = 成功）。
type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGameReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// RejoinMsg 是 match → game 的回局查询（route "game.rejoin"）：问这个 game 节点
// 是否托管着该 token 的存量实例。
type RejoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RejoinMsg) Reset() {
	*x = RejoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinMsg) ProtoMessage() {}

func (x *RejoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinMsg.ProtoReflect.Descriptor instead.
func (*RejoinMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{11}
}

func (x *RejoinMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RejoinReply 是 game.rejoin 的应答。
type RejoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found     bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	MatchId   string `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIdx int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"` // 原本的玩家槽位（0/1）
}

func (x *RejoinReply) Reset() {
	*x = RejoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinReply) ProtoMessage() {}

func (x *RejoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinReply.ProtoReflect.Descriptor instead.
func (*RejoinReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{12}
}

func (x *RejoinReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RejoinReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RejoinReply) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// LeaveMsg 是 match → game 的 RPC（route "game.game.leave"）：请托管该实例的 game
// 节点把这个玩家从对局里释放出来（见 AbandonMatchMsg 的语义）。uid 是会话 UID。
type LeaveMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *LeaveMsg) Reset() {
	*x = LeaveMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMsg) ProtoMessage() {}

func (x *LeaveMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMsg.ProtoReflect.Descriptor instead.
func (*LeaveMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveMsg) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// LeaveReply 是 game.leave 的应答。ok=false 表示这个 game 节点上没有该 uid 的实例
// （已经离场、或本来就不在这个节点上）。
type LeaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *LeaveReply) Reset() {
	*x = LeaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveReply) ProtoMessage() {}

func (x *LeaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveReply.ProtoReflect.Descriptor instead.
func (*LeaveReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{14}
}

func (x *LeaveReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// game → logic：一局分出胜负时的结算上报（remote route logic.logic.recordmatch）。
type RecordMatchMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId         string        `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Slots           []*SlotResult `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	WinnerSlot      int32         `protobuf:"varint,3,opt,name=winner_slot,json=winnerSlot,proto3" json:"winner_slot,omitempty"`
	DurationSeconds int32         `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
}

func (x *RecordMatchMsg) Reset() {
	*x = RecordMatchMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordMatchMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMatchMsg) ProtoMessage() {}

func (x *RecordMatchMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMatchMsg.ProtoReflect.Descriptor instead.
func (*RecordMatchMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{15}
}

func (x *RecordMatchMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RecordMatchMsg) GetSlots() []*SlotResult {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *RecordMatchMsg) GetWinnerSlot() int32 {
	if x != nil {
		return x.WinnerSlot
	}
	return 0
}

func (x *RecordMatchMsg) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type RecordMatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Applied bool   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"` // false = 收到但按规则未入账
	Reason  string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *RecordMatchReply) Reset() {
	*x = RecordMatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMatchReply) ProtoMessage() {}

func (x *RecordMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMatchReply.ProtoReflect.Descriptor instead.
func (*RecordMatchReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{16}
}

func (x *RecordMatchReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RecordMatchReply) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *RecordMatchReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserOnlineMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *UserOnlineMsg) Reset() {
	*x = UserOnlineMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineMsg) ProtoMessage() {}

func (x *UserOnlineMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineMsg.ProtoReflect.Descriptor instead.
func (*UserOnlineMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{17}
}

func (x *UserOnlineMsg) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UserOnlineReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UserOnlineReply) Reset() {
	*x = UserOnlineReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineReply) ProtoMessage() {}

func (x *UserOnlineReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineReply.ProtoReflect.Descriptor instead.
func (*UserOnlineReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{18}
}

func (x *UserOnlineReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UserOnlineReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AddBotsMsg 是 gm → match 的 RPC（route "match.match.addbots"）：往匹配队列里
// 塞 N 个机器人凑人数。
//
// 这条 route 不会从客户端到达（不在 gate 的转发白名单里），因此不做调用方鉴权；
// 集群内部进程本就能调它，那不是鉴权能解决的问题。
type AddBotsMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 期望入队的机器人数量，服务端另有单次上限
}

func (x *AddBotsMsg) Reset() {
	*x = AddBotsMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBotsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBotsMsg) ProtoMessage() {}

func (x *AddBotsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBotsMsg.ProtoReflect.Descriptor instead.
func (*AddBotsMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{19}
}

func (x *AddBotsMsg) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AddBotsReply 是 match.match.addbots 的应答。
// reason：internal | noop（count<=0 时的空操作，ok 仍为 true）。
type AddBotsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Enqueued int32  `protobuf:"varint,2,opt,name=enqueued,proto3" json:"enqueued,omitempty"` // 实际入队数量
	Reason   string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AddBotsReply) Reset() {
	*x = AddBotsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBotsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBotsReply) ProtoMessage() {}

func (x *AddBotsReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBotsReply.ProtoReflect.Descriptor instead.
func (*AddBotsReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{20}
}

func (x *AddBotsReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddBotsReply) GetEnqueued() int32 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *AddBotsReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GrantCoinsMsg 是 gm → logic 的 RPC（route "logic.logic.grantcoins"）：
// 给指定账号加（delta>0）或扣（delta<0）金币。用户名 → accountID 的解析在 gm 侧完成。
type GrantCoinsMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Delta     int64  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *GrantCoinsMsg) Reset() {
	*x = GrantCoinsMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantCoinsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantCoinsMsg) ProtoMessage() {}

func (x *GrantCoinsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantCoinsMsg.ProtoReflect.Descriptor instead.
func (*GrantCoinsMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{21}
}

func (x *GrantCoinsMsg) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GrantCoinsMsg) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

// GrantCoinsReply 是 logic.logic.grantcoins 的应答。
// reason：account_not_found | unauthenticated | profile_missing | internal。
type GrantCoinsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Coins  int64  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"` // 变更后的余额（ok=true 时有效）
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GrantCoinsReply) Reset() {
	*x = GrantCoinsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantCoinsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantCoinsReply) ProtoMessage() {}

func (x *GrantCoinsReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantCoinsReply.ProtoReflect.Descriptor instead.
func (*GrantCoinsReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{22}
}

func (x *GrantCoinsReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GrantCoinsReply) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *GrantCoinsReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_game_protos_game_proto protoreflect.FileDescriptor

var file_game_protos_game_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x45,
	0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x4d, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x29, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x66, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a,
	0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x74, 0x0a, 0x0b, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x03,
	0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x73, 0x65, 0x74, 0x22,
	0x84, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x75, 0x6c,
	0x6c, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x24, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x60, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x61, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65,
	0x61, 0x74, 0x68, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x6c, 0x6f,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x6c, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x7f, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x47, 0x61,
	0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x78, 0x22, 0x25, 0x0a, 0x0d, 0x42, 0x69, 0x6e, 0x64, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x3e,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x25,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x4d,
	0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5d, 0x0a, 0x0b, 0x52, 0x65, 0x6a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x78, 0x22, 0x1c, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x9f, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x0d, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x74,
	0x73, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x42, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x44,
	0x0a, 0x0d, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x4d, 0x73, 0x67, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x0f, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x69,
	0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x14, 0x5a, 0x12, 0x6a, 0x6f, 0x6c, 0x74, 0x67, 0x6f, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_game_protos_game_proto_rawDescOnce sync.Once
	file_game_protos_game_proto_rawDescData = file_game_protos_game_proto_rawDesc
)

func file_game_protos_game_proto_rawDescGZIP() []byte {
	file_game_protos_game_proto_rawDescOnce.Do(func() {
		file_game_protos_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_protos_game_proto_rawDescData)
	})
	return file_game_protos_game_proto_rawDescData
}

var file_game_protos_game_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_game_protos_game_proto_goTypes = []any{
	(*SchemaField)(nil),      // 0: game.SchemaField
	(*Schema)(nil),           // 1: game.Schema
	(*AttrValue)(nil),        // 2: game.AttrValue
	(*EntityDelta)(nil),      // 3: game.EntityDelta
	(*Frame)(nil),            // 4: game.Frame
	(*SlotResult)(nil),       // 5: game.SlotResult
	(*MatchEnded)(nil),       // 6: game.MatchEnded
	(*BindGameMsg)(nil),      // 7: game.BindGameMsg
	(*BindGameReply)(nil),    // 8: game.BindGameReply
	(*CreateGameMsg)(nil),    // 9: game.CreateGameMsg
	(*CreateGameReply)(nil),  // 10: game.CreateGameReply
	(*RejoinMsg)(nil),        // 11: game.RejoinMsg
	(*RejoinReply)(nil),      // 12: game.RejoinReply
	(*LeaveMsg)(nil),         // 13: game.LeaveMsg
	(*LeaveReply)(nil),       // 14: game.LeaveReply
	(*RecordMatchMsg)(nil),   // 15: game.RecordMatchMsg
	(*RecordMatchReply)(nil), // 16: game.RecordMatchReply
	(*UserOnlineMsg)(nil),    // 17: game.UserOnlineMsg
	(*UserOnlineReply)(nil),  // 18: game.UserOnlineReply
	(*AddBotsMsg)(nil),       // 19: game.AddBotsMsg
	(*AddBotsReply)(nil),     // 20: game.AddBotsReply
	(*GrantCoinsMsg)(nil),    // 21: game.GrantCoinsMsg
	(*GrantCoinsReply)(nil),  // 22: game.GrantCoinsReply
}
var file_game_protos_game_proto_depIdxs = []int32{
	0, // 0: game.Schema.fields:type_name -> game.SchemaField
	2, // 1: game.EntityDelta.set:type_name -> game.AttrValue
	3, // 2: game.Frame.entities:type_name -> game.EntityDelta
	1, // 3: game.Frame.schema:type_name -> game.Schema
	5, // 4: game.MatchEnded.slots:type_name -> game.SlotResult
	5, // 5: game.RecordMatchMsg.slots:type_name -> game.SlotResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_game_protos_game_proto_init() }
func file_game_protos_game_proto_init() {
	if File_game_protos_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_protos_game_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SchemaField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AttrValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EntityDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SlotResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MatchEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BindGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BindGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*LeaveMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*LeaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RecordMatchMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RecordMatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UserOnlineMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UserOnlineReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AddBotsMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*AddBotsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*GrantCoinsMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GrantCoinsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_protos_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_protos_game_proto_goTypes,
		DependencyIndexes: file_game_protos_game_proto_depIdxs,
		MessageInfos:      file_game_protos_game_proto_msgTypes,
	}.Build()
	File_game_protos_game_proto = out.File
	file_game_protos_game_proto_rawDesc = nil
	file_game_protos_game_proto_goTypes = nil
	file_game_protos_game_proto_depIdxs = nil
}
