// 游戏协议消息（wire 契约）。gate / match / game 三服务与 Godot 客户端都遵守：
//   - 客户端 → gate → match：match.join（JoinMsg，Notify）
//   - match → 客户端：onMatched（MatchResult，Push）
//   - match → game（RPC）：game.create（CreateGameMsg）/ game.rejoin（RejoinMsg）
//   - 客户端 → gate → game：game.cmd（CommandMsg）/ game.resync（空，Notify）
//   - game → 客户端：onFrame（Frame，Push）
//
// 同步不走手写快照，走通用「实体-属性」增量：属性表（Schema）在 full 帧里下发一次，
// 之后所有帧都是 (实体, 属性, 终值) 的 op。新增属性不需要改动本文件的字段定义。
//
// 序列化用 pitaya 的 protobuf serializer。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: game/protos/game.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InputMsg 是玩家移动输入（世界空间水平速度 + 跳跃边沿）。
type InputMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move []float32 `protobuf:"fixed32,1,rep,packed,name=move,proto3" json:"move,omitempty"` // [wx, wz]，世界空间水平期望速度（m/s）
	Jump bool      `protobuf:"varint,2,opt,name=jump,proto3" json:"jump,omitempty"`         // 跳跃边沿触发（服务端下一 tick 消费）
	Yaw  float32   `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`          // 水平朝向（弧度，绕 Y 轴，客户端相机 yaw）
}

func (x *InputMsg) Reset() {
	*x = InputMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMsg) ProtoMessage() {}

func (x *InputMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMsg.ProtoReflect.Descriptor instead.
func (*InputMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{0}
}

func (x *InputMsg) GetMove() []float32 {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *InputMsg) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *InputMsg) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// ShootMsg 是射击请求（枪口起点 + 朝向，朝向会被服务端归一化）。
type ShootMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin []float32 `protobuf:"fixed32,1,rep,packed,name=origin,proto3" json:"origin,omitempty"` // [x, y, z]
	Dir    []float32 `protobuf:"fixed32,2,rep,packed,name=dir,proto3" json:"dir,omitempty"`       // [x, y, z]
}

func (x *ShootMsg) Reset() {
	*x = ShootMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootMsg) ProtoMessage() {}

func (x *ShootMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootMsg.ProtoReflect.Descriptor instead.
func (*ShootMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{1}
}

func (x *ShootMsg) GetOrigin() []float32 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ShootMsg) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

// CommandMsg 是一帧的上行命令：把输入、射击、重置合并成一条消息发送
// （帧是最小发送单位）。shoot/reset 是边沿触发，未触发时为 false。
type CommandMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move   []float32 `protobuf:"fixed32,1,rep,packed,name=move,proto3" json:"move,omitempty"`     // [wx, wz]，世界空间水平期望速度（m/s）
	Yaw    float32   `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`              // 水平朝向（弧度，绕 Y 轴）
	Jump   bool      `protobuf:"varint,3,opt,name=jump,proto3" json:"jump,omitempty"`             // 跳跃边沿触发（服务端下一 tick 消费）
	Shoot  bool      `protobuf:"varint,4,opt,name=shoot,proto3" json:"shoot,omitempty"`           // 射击边沿触发
	Origin []float32 `protobuf:"fixed32,5,rep,packed,name=origin,proto3" json:"origin,omitempty"` // [x, y, z] 枪口位置（shoot 为 true 时有效）
	Dir    []float32 `protobuf:"fixed32,6,rep,packed,name=dir,proto3" json:"dir,omitempty"`       // [x, y, z] 射击方向（服务端会归一化）
	Reset_ bool      `protobuf:"varint,7,opt,name=reset,proto3" json:"reset,omitempty"`           // 重建场景边沿触发
}

func (x *CommandMsg) Reset() {
	*x = CommandMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMsg) ProtoMessage() {}

func (x *CommandMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMsg.ProtoReflect.Descriptor instead.
func (*CommandMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{2}
}

func (x *CommandMsg) GetMove() []float32 {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *CommandMsg) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *CommandMsg) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *CommandMsg) GetShoot() bool {
	if x != nil {
		return x.Shoot
	}
	return false
}

func (x *CommandMsg) GetOrigin() []float32 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CommandMsg) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *CommandMsg) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

// JoinMsg 是加入匹配的请求。token 是客户端持久化的身份（首次运行生成并存储），
// 服务端把它当作会话 UID：重连时同一个 token 能找回原来的对局实例。
type JoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JoinMsg) Reset() {
	*x = JoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMsg) ProtoMessage() {}

func (x *JoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMsg.ProtoReflect.Descriptor instead.
func (*JoinMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{3}
}

func (x *JoinMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// MatchResult 是匹配成功结果（match → 客户端 push route "onMatched"）。
type MatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId      string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                  // 对局 id
	GameServerId string `protobuf:"bytes,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"` // 分配到的 game 节点 id
	PlayerIdx    int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"`           // 本客户端在局内的玩家槽位（0/1）
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{4}
}

func (x *MatchResult) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResult) GetGameServerId() string {
	if x != nil {
		return x.GameServerId
	}
	return ""
}

func (x *MatchResult) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// CreateGameMsg 是 match → game 创建对局的 RPC 请求（route "game.create"）。
// uids 按槽位顺序（下标即 player_idx），1 个 = 单人兜底局。
type CreateGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string   `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Uids    []string `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *CreateGameMsg) Reset() {
	*x = CreateGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameMsg) ProtoMessage() {}

func (x *CreateGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameMsg.ProtoReflect.Descriptor instead.
func (*CreateGameMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGameMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateGameMsg) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

// CreateGameReply 是 game.create 的 RPC 应答（0 = 成功）。
type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// RejoinMsg 是 match → game 的回局查询（route "game.rejoin"）：问这个 game 节点
// 是否托管着该 token 的存量实例。
type RejoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RejoinMsg) Reset() {
	*x = RejoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinMsg) ProtoMessage() {}

func (x *RejoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinMsg.ProtoReflect.Descriptor instead.
func (*RejoinMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{7}
}

func (x *RejoinMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RejoinReply 是 game.rejoin 的应答。
type RejoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found     bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	MatchId   string `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIdx int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"` // 原本的玩家槽位（0/1）
}

func (x *RejoinReply) Reset() {
	*x = RejoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinReply) ProtoMessage() {}

func (x *RejoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinReply.ProtoReflect.Descriptor instead.
func (*RejoinReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{8}
}

func (x *RejoinReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RejoinReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RejoinReply) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// SchemaField 是一个同步属性的声明。
type SchemaField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 属性 ID（Frame 里的 AttrValue.id）
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 属性名，客户端按名字取值
	Kind int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"` // 值类型，与 replication.Kind 取值一致
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{9}
}

func (x *SchemaField) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// Schema 是属性表，随 full 帧下发。
type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields  []*SchemaField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Version uint32         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 属性表哈希，客户端据此检测前后端不一致
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{10}
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// AttrValue 是一个属性的取值。按 schema 声明的 kind 取用其中一个字段。
type AttrValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	F  []float32 `protobuf:"fixed32,2,rep,packed,name=f,proto3" json:"f,omitempty"` // KindF32(1 项) / KindVec2(2) / KindVec3(3) / KindVec4(4)
	I  int32     `protobuf:"varint,3,opt,name=i,proto3" json:"i,omitempty"`         // KindI32
	B  bool      `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`         // KindBool
	S  string    `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"`          // KindStr
}

func (x *AttrValue) Reset() {
	*x = AttrValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrValue) ProtoMessage() {}

func (x *AttrValue) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrValue.ProtoReflect.Descriptor instead.
func (*AttrValue) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{11}
}

func (x *AttrValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrValue) GetF() []float32 {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *AttrValue) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *AttrValue) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *AttrValue) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// EntityDelta 是一个实体在本帧的变化。应用顺序：destroy → removed → set。
type EntityDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Destroy bool         `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"`
	Removed []uint32     `protobuf:"varint,3,rep,packed,name=removed,proto3" json:"removed,omitempty"`
	Set     []*AttrValue `protobuf:"bytes,4,rep,name=set,proto3" json:"set,omitempty"`
}

func (x *EntityDelta) Reset() {
	*x = EntityDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDelta) ProtoMessage() {}

func (x *EntityDelta) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDelta.ProtoReflect.Descriptor instead.
func (*EntityDelta) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{12}
}

func (x *EntityDelta) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDelta) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *EntityDelta) GetRemoved() []uint32 {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *EntityDelta) GetSet() []*AttrValue {
	if x != nil {
		return x.Set
	}
	return nil
}

// Frame 是一帧同步消息。full=true 表示全量帧（重连 / 首次进入），客户端应先
// 清空本地状态再整体覆盖；此时 schema 一并携带。
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step     int32          `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"` // 帧号（= 服务端 tick 计数）
	Full     bool           `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	Entities []*EntityDelta `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	Schema   *Schema        `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{13}
}

func (x *Frame) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Frame) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *Frame) GetEntities() []*EntityDelta {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Frame) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_game_protos_game_proto protoreflect.FileDescriptor

var file_game_protos_game_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x44,
	0x0a, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a, 0x75,
	0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x79, 0x61, 0x77, 0x22, 0x34, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x4d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x79, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x12,
	0x12, 0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a,
	0x75, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03,
	0x64, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x07, 0x4a, 0x6f, 0x69,
	0x6e, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x6d, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x78, 0x22, 0x3e, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x5d, 0x0a, 0x0b, 0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x78, 0x22, 0x45, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x4d, 0x0a, 0x06, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x01, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x69, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x12,
	0x0c, 0x0a, 0x01, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x74, 0x0a,
	0x0b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x12, 0x21, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03,
	0x73, 0x65, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x14, 0x5a, 0x12, 0x6a, 0x6f,
	0x6c, 0x74, 0x67, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_protos_game_proto_rawDescOnce sync.Once
	file_game_protos_game_proto_rawDescData = file_game_protos_game_proto_rawDesc
)

func file_game_protos_game_proto_rawDescGZIP() []byte {
	file_game_protos_game_proto_rawDescOnce.Do(func() {
		file_game_protos_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_protos_game_proto_rawDescData)
	})
	return file_game_protos_game_proto_rawDescData
}

var file_game_protos_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_protos_game_proto_goTypes = []any{
	(*InputMsg)(nil),        // 0: game.InputMsg
	(*ShootMsg)(nil),        // 1: game.ShootMsg
	(*CommandMsg)(nil),      // 2: game.CommandMsg
	(*JoinMsg)(nil),         // 3: game.JoinMsg
	(*MatchResult)(nil),     // 4: game.MatchResult
	(*CreateGameMsg)(nil),   // 5: game.CreateGameMsg
	(*CreateGameReply)(nil), // 6: game.CreateGameReply
	(*RejoinMsg)(nil),       // 7: game.RejoinMsg
	(*RejoinReply)(nil),     // 8: game.RejoinReply
	(*SchemaField)(nil),     // 9: game.SchemaField
	(*Schema)(nil),          // 10: game.Schema
	(*AttrValue)(nil),       // 11: game.AttrValue
	(*EntityDelta)(nil),     // 12: game.EntityDelta
	(*Frame)(nil),           // 13: game.Frame
}
var file_game_protos_game_proto_depIdxs = []int32{
	9,  // 0: game.Schema.fields:type_name -> game.SchemaField
	11, // 1: game.EntityDelta.set:type_name -> game.AttrValue
	12, // 2: game.Frame.entities:type_name -> game.EntityDelta
	10, // 3: game.Frame.schema:type_name -> game.Schema
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_game_protos_game_proto_init() }
func file_game_protos_game_proto_init() {
	if File_game_protos_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_protos_game_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InputMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShootMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CommandMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*JoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SchemaField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AttrValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*EntityDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_protos_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_protos_game_proto_goTypes,
		DependencyIndexes: file_game_protos_game_proto_depIdxs,
		MessageInfos:      file_game_protos_game_proto_msgTypes,
	}.Build()
	File_game_protos_game_proto = out.File
	file_game_protos_game_proto_rawDesc = nil
	file_game_protos_game_proto_goTypes = nil
	file_game_protos_game_proto_depIdxs = nil
}
