// 游戏协议消息（wire 契约）。gate / match / game 三服务与 Godot 客户端都遵守。
// 线上 route 一律是三段式 `server.service.method`（pitaya 的路由格式）：
//   - 客户端 → gate → account：account.account.register / account.account.login /
//     account.account.resume（Request/Response，不是 Notify/Push —— 见 docs/API.md）
//   - 客户端 → gate → match：match.match.join（JoinMsg，Notify）
//   - match → 客户端：onMatched（MatchResult，Push —— 推送用 route 名，不是三段式）
//   - match → game（RPC）：game.game.create（CreateGameMsg）/ game.game.rejoin（RejoinMsg）
//   - match → gate（RPC）：gate.gate.bindgame（BindGameMsg）
//   - 客户端 → gate → game：game.game.cmd（CommandMsg）/ game.game.resync（空，Notify）
//   - game → 客户端：onFrame（Frame，Push）
//
// 同步不走手写快照，走通用「实体-属性」增量：属性表（Schema）在 full 帧里下发一次，
// 之后所有帧都是 (实体, 属性, 终值) 的 op。新增属性不需要改动本文件的字段定义。
//
// 序列化用 pitaya 的 protobuf serializer。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: game/protos/game.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandMsg 是一帧的上行命令：把输入、射击、重置合并成一条消息发送
// （帧是最小发送单位）。shoot/reset 是边沿触发，未触发时为 false。
type CommandMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move   []float32 `protobuf:"fixed32,1,rep,packed,name=move,proto3" json:"move,omitempty"`     // [wx, wz]，世界空间水平期望速度（m/s）
	Yaw    float32   `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`              // 水平朝向（弧度，绕 Y 轴）
	Jump   bool      `protobuf:"varint,3,opt,name=jump,proto3" json:"jump,omitempty"`             // 跳跃边沿触发（服务端下一 tick 消费）
	Shoot  bool      `protobuf:"varint,4,opt,name=shoot,proto3" json:"shoot,omitempty"`           // 射击边沿触发
	Origin []float32 `protobuf:"fixed32,5,rep,packed,name=origin,proto3" json:"origin,omitempty"` // [x, y, z] 枪口位置（shoot 为 true 时有效）
	Dir    []float32 `protobuf:"fixed32,6,rep,packed,name=dir,proto3" json:"dir,omitempty"`       // [x, y, z] 射击方向（服务端会归一化）
	Reset_ bool      `protobuf:"varint,7,opt,name=reset,proto3" json:"reset,omitempty"`           // 重建场景边沿触发
}

func (x *CommandMsg) Reset() {
	*x = CommandMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMsg) ProtoMessage() {}

func (x *CommandMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMsg.ProtoReflect.Descriptor instead.
func (*CommandMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{0}
}

func (x *CommandMsg) GetMove() []float32 {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *CommandMsg) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *CommandMsg) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *CommandMsg) GetShoot() bool {
	if x != nil {
		return x.Shoot
	}
	return false
}

func (x *CommandMsg) GetOrigin() []float32 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CommandMsg) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *CommandMsg) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

// JoinMsg 是加入匹配的请求。身份来自会话绑定（account 服务在登录时做的），
// 这里不再携带任何凭证 —— 字段清空后 route 与 handler 签名都不变。
type JoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinMsg) Reset() {
	*x = JoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMsg) ProtoMessage() {}

func (x *JoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMsg.ProtoReflect.Descriptor instead.
func (*JoinMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{1}
}

// RegisterMsg 是注册请求。用户名 3-16 位 [a-zA-Z0-9_]，密码 6-64 位。
type RegisterMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginMsg 是登录请求。
type LoginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginMsg) Reset() {
	*x = LoginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMsg) ProtoMessage() {}

func (x *LoginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMsg.ProtoReflect.Descriptor instead.
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{3}
}

func (x *LoginMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ResumeMsg 是凭证恢复请求：客户端持有 token，换回会话。
type ResumeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResumeMsg) Reset() {
	*x = ResumeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeMsg) ProtoMessage() {}

func (x *ResumeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeMsg.ProtoReflect.Descriptor instead.
func (*ResumeMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginReply 是 register / login / resume 的统一应答，客户端用同一段代码处理。
// ok=false 时 reason 是机器可读的原因码（bad_credentials / name_taken /
// bad_username / bad_password / rate_limited / token_invalid / internal）。
type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                          // ok=true 时有效
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                    // 保留用户输入的原始大小写，供 UI 显示
	AccountId string `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 十进制字符串，仅供诊断
	Reason    string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                        // ok=false 时的原因码
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReply) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogicStateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogicStateMsg) Reset() {
	*x = LogicStateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicStateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicStateMsg) ProtoMessage() {}

func (x *LogicStateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicStateMsg.ProtoReflect.Descriptor instead.
func (*LogicStateMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{6}
}

type PurchaseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *PurchaseMsg) Reset() {
	*x = PurchaseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseMsg) ProtoMessage() {}

func (x *PurchaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseMsg.ProtoReflect.Descriptor instead.
func (*PurchaseMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{7}
}

func (x *PurchaseMsg) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PurchaseMsg) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type EquipMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *EquipMsg) Reset() {
	*x = EquipMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipMsg) ProtoMessage() {}

func (x *EquipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipMsg.ProtoReflect.Descriptor instead.
func (*EquipMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{8}
}

func (x *EquipMsg) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type UserOnlineMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *UserOnlineMsg) Reset() {
	*x = UserOnlineMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineMsg) ProtoMessage() {}

func (x *UserOnlineMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineMsg.ProtoReflect.Descriptor instead.
func (*UserOnlineMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{9}
}

func (x *UserOnlineMsg) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UserOnlineReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UserOnlineReply) Reset() {
	*x = UserOnlineReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineReply) ProtoMessage() {}

func (x *UserOnlineReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineReply.ProtoReflect.Descriptor instead.
func (*UserOnlineReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{10}
}

func (x *UserOnlineReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UserOnlineReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogicShopItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId        string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Price         int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	EquipSlot     string `protobuf:"bytes,4,opt,name=equip_slot,json=equipSlot,proto3" json:"equip_slot,omitempty"`
	OwnedQuantity int64  `protobuf:"varint,5,opt,name=owned_quantity,json=ownedQuantity,proto3" json:"owned_quantity,omitempty"`
}

func (x *LogicShopItem) Reset() {
	*x = LogicShopItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicShopItem) ProtoMessage() {}

func (x *LogicShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicShopItem.ProtoReflect.Descriptor instead.
func (*LogicShopItem) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{11}
}

func (x *LogicShopItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LogicShopItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LogicShopItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LogicShopItem) GetEquipSlot() string {
	if x != nil {
		return x.EquipSlot
	}
	return ""
}

func (x *LogicShopItem) GetOwnedQuantity() int64 {
	if x != nil {
		return x.OwnedQuantity
	}
	return 0
}

type LogicStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                    bool             `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason                string           `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Coins                 int64            `protobuf:"varint,3,opt,name=coins,proto3" json:"coins,omitempty"`
	Items                 []*LogicShopItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	EquippedPrimaryWeapon string           `protobuf:"bytes,5,opt,name=equipped_primary_weapon,json=equippedPrimaryWeapon,proto3" json:"equipped_primary_weapon,omitempty"`
}

func (x *LogicStateReply) Reset() {
	*x = LogicStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogicStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicStateReply) ProtoMessage() {}

func (x *LogicStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicStateReply.ProtoReflect.Descriptor instead.
func (*LogicStateReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{12}
}

func (x *LogicStateReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LogicStateReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LogicStateReply) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *LogicStateReply) GetItems() []*LogicShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LogicStateReply) GetEquippedPrimaryWeapon() string {
	if x != nil {
		return x.EquippedPrimaryWeapon
	}
	return ""
}

// BindGameMsg 是 match → gate 的 RPC 请求（route "gate.gate.bindgame"）：请玩家
// 所属的 gate 把对局归属写进它自己的会话数据（gate 据 gameServerId 定点路由
// game.*）。game_server_id 为空表示回滚（清掉归属）。
type BindGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameServerId string `protobuf:"bytes,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"`
	MatchId      string `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIdx    int32  `protobuf:"varint,4,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"`
}

func (x *BindGameMsg) Reset() {
	*x = BindGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGameMsg) ProtoMessage() {}

func (x *BindGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGameMsg.ProtoReflect.Descriptor instead.
func (*BindGameMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{13}
}

func (x *BindGameMsg) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BindGameMsg) GetGameServerId() string {
	if x != nil {
		return x.GameServerId
	}
	return ""
}

func (x *BindGameMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *BindGameMsg) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// BindGameReply 是 gate.gate.bindgame 的应答。found=false 表示该 gate 上没有
// 这个会话（玩家已掉线）。
type BindGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *BindGameReply) Reset() {
	*x = BindGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGameReply) ProtoMessage() {}

func (x *BindGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGameReply.ProtoReflect.Descriptor instead.
func (*BindGameReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{14}
}

func (x *BindGameReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// MatchResult 是匹配成功结果（match → 客户端 push route "onMatched"）。
type MatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId      string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                  // 对局 id
	GameServerId string `protobuf:"bytes,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"` // 分配到的 game 节点 id
	PlayerIdx    int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"`           // 本客户端在局内的玩家槽位（0/1）
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{15}
}

func (x *MatchResult) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResult) GetGameServerId() string {
	if x != nil {
		return x.GameServerId
	}
	return ""
}

func (x *MatchResult) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// CreateGameMsg 是 match → game 创建对局的 RPC 请求（route "game.create"）。
// uids 按槽位顺序（下标即 player_idx），1 个 = 单人兜底局。
type CreateGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string   `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Uids    []string `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *CreateGameMsg) Reset() {
	*x = CreateGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameMsg) ProtoMessage() {}

func (x *CreateGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameMsg.ProtoReflect.Descriptor instead.
func (*CreateGameMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{16}
}

func (x *CreateGameMsg) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateGameMsg) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

// CreateGameReply 是 game.create 的 RPC 应答（0 = 成功）。
type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{17}
}

func (x *CreateGameReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// RejoinMsg 是 match → game 的回局查询（route "game.rejoin"）：问这个 game 节点
// 是否托管着该 token 的存量实例。
type RejoinMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RejoinMsg) Reset() {
	*x = RejoinMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinMsg) ProtoMessage() {}

func (x *RejoinMsg) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinMsg.ProtoReflect.Descriptor instead.
func (*RejoinMsg) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{18}
}

func (x *RejoinMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RejoinReply 是 game.rejoin 的应答。
type RejoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found     bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	MatchId   string `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIdx int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"` // 原本的玩家槽位（0/1）
}

func (x *RejoinReply) Reset() {
	*x = RejoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejoinReply) ProtoMessage() {}

func (x *RejoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejoinReply.ProtoReflect.Descriptor instead.
func (*RejoinReply) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{19}
}

func (x *RejoinReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RejoinReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RejoinReply) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// SchemaField 是一个同步属性的声明。
type SchemaField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 属性 ID（Frame 里的 AttrValue.id）
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 属性名，客户端按名字取值
	Kind int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"` // 值类型，与 replication.Kind 取值一致
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{20}
}

func (x *SchemaField) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// Schema 是属性表，随 full 帧下发。
type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields  []*SchemaField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Version uint32         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 属性表哈希，客户端据此检测前后端不一致
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{21}
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// AttrValue 是一个属性的取值。按 schema 声明的 kind 取用其中一个字段。
type AttrValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	F  []float32 `protobuf:"fixed32,2,rep,packed,name=f,proto3" json:"f,omitempty"` // KindF32(1 项) / KindVec2(2) / KindVec3(3) / KindVec4(4)
	I  int32     `protobuf:"varint,3,opt,name=i,proto3" json:"i,omitempty"`         // KindI32
	B  bool      `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`         // KindBool
	S  string    `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"`          // KindStr
}

func (x *AttrValue) Reset() {
	*x = AttrValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrValue) ProtoMessage() {}

func (x *AttrValue) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrValue.ProtoReflect.Descriptor instead.
func (*AttrValue) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{22}
}

func (x *AttrValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrValue) GetF() []float32 {
	if x != nil {
		return x.F
	}
	return nil
}

func (x *AttrValue) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *AttrValue) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *AttrValue) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// EntityDelta 是一个实体在本帧的变化。应用顺序：destroy → removed → set。
type EntityDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Destroy bool         `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"`
	Removed []uint32     `protobuf:"varint,3,rep,packed,name=removed,proto3" json:"removed,omitempty"`
	Set     []*AttrValue `protobuf:"bytes,4,rep,name=set,proto3" json:"set,omitempty"`
}

func (x *EntityDelta) Reset() {
	*x = EntityDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDelta) ProtoMessage() {}

func (x *EntityDelta) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDelta.ProtoReflect.Descriptor instead.
func (*EntityDelta) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{23}
}

func (x *EntityDelta) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDelta) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *EntityDelta) GetRemoved() []uint32 {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *EntityDelta) GetSet() []*AttrValue {
	if x != nil {
		return x.Set
	}
	return nil
}

// Frame 是一帧同步消息。full=true 表示全量帧（重连 / 首次进入），客户端应先
// 清空本地状态再整体覆盖；此时 schema 一并携带。
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step     int32          `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"` // 帧号（= 服务端 tick 计数）
	Full     bool           `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	Entities []*EntityDelta `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	Schema   *Schema        `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_protos_game_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_game_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_game_protos_game_proto_rawDescGZIP(), []int{24}
}

func (x *Frame) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Frame) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *Frame) GetEntities() []*EntityDelta {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Frame) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_game_protos_game_proto protoreflect.FileDescriptor

var file_game_protos_game_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x9c,
	0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x79, 0x61, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0x09, 0x0a,
	0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x42, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x0f,
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x22,
	0x42, 0x0a, 0x0b, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x08, 0x45, 0x71, 0x75, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x68, 0x6f,
	0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x5f,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x6f, 0x77, 0x6e, 0x65, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xb2, 0x01,
	0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x69,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x12,
	0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x68, 0x6f, 0x70, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x77,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x70, 0x65, 0x64, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x22, 0x7f, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x78, 0x22, 0x25, 0x0a, 0x0d, 0x42, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x6d, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x78, 0x22, 0x3e, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x5d, 0x0a, 0x0b, 0x52, 0x65, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x78, 0x22, 0x45, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x4d, 0x0a, 0x06, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x01, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x69, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x12,
	0x0c, 0x0a, 0x01, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x74, 0x0a,
	0x0b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x12, 0x21, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03,
	0x73, 0x65, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x14, 0x5a, 0x12, 0x6a, 0x6f,
	0x6c, 0x74, 0x67, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_protos_game_proto_rawDescOnce sync.Once
	file_game_protos_game_proto_rawDescData = file_game_protos_game_proto_rawDesc
)

func file_game_protos_game_proto_rawDescGZIP() []byte {
	file_game_protos_game_proto_rawDescOnce.Do(func() {
		file_game_protos_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_protos_game_proto_rawDescData)
	})
	return file_game_protos_game_proto_rawDescData
}

var file_game_protos_game_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_game_protos_game_proto_goTypes = []any{
	(*CommandMsg)(nil),      // 0: game.CommandMsg
	(*JoinMsg)(nil),         // 1: game.JoinMsg
	(*RegisterMsg)(nil),     // 2: game.RegisterMsg
	(*LoginMsg)(nil),        // 3: game.LoginMsg
	(*ResumeMsg)(nil),       // 4: game.ResumeMsg
	(*LoginReply)(nil),      // 5: game.LoginReply
	(*LogicStateMsg)(nil),   // 6: game.LogicStateMsg
	(*PurchaseMsg)(nil),     // 7: game.PurchaseMsg
	(*EquipMsg)(nil),        // 8: game.EquipMsg
	(*UserOnlineMsg)(nil),   // 9: game.UserOnlineMsg
	(*UserOnlineReply)(nil), // 10: game.UserOnlineReply
	(*LogicShopItem)(nil),   // 11: game.LogicShopItem
	(*LogicStateReply)(nil), // 12: game.LogicStateReply
	(*BindGameMsg)(nil),     // 13: game.BindGameMsg
	(*BindGameReply)(nil),   // 14: game.BindGameReply
	(*MatchResult)(nil),     // 15: game.MatchResult
	(*CreateGameMsg)(nil),   // 16: game.CreateGameMsg
	(*CreateGameReply)(nil), // 17: game.CreateGameReply
	(*RejoinMsg)(nil),       // 18: game.RejoinMsg
	(*RejoinReply)(nil),     // 19: game.RejoinReply
	(*SchemaField)(nil),     // 20: game.SchemaField
	(*Schema)(nil),          // 21: game.Schema
	(*AttrValue)(nil),       // 22: game.AttrValue
	(*EntityDelta)(nil),     // 23: game.EntityDelta
	(*Frame)(nil),           // 24: game.Frame
}
var file_game_protos_game_proto_depIdxs = []int32{
	11, // 0: game.LogicStateReply.items:type_name -> game.LogicShopItem
	20, // 1: game.Schema.fields:type_name -> game.SchemaField
	22, // 2: game.EntityDelta.set:type_name -> game.AttrValue
	23, // 3: game.Frame.entities:type_name -> game.EntityDelta
	21, // 4: game.Frame.schema:type_name -> game.Schema
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_game_protos_game_proto_init() }
func file_game_protos_game_proto_init() {
	if File_game_protos_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_protos_game_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommandMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LoginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LogicStateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PurchaseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EquipMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UserOnlineMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UserOnlineReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*LogicShopItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LogicStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*BindGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*BindGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*MatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RejoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SchemaField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*AttrValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*EntityDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_protos_game_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_protos_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_protos_game_proto_goTypes,
		DependencyIndexes: file_game_protos_game_proto_depIdxs,
		MessageInfos:      file_game_protos_game_proto_msgTypes,
	}.Build()
	File_game_protos_game_proto = out.File
	file_game_protos_game_proto_rawDesc = nil
	file_game_protos_game_proto_goTypes = nil
	file_game_protos_game_proto_depIdxs = nil
}
