// match 推给客户端的消息。
//
// 归属规则：**推送按发送方** —— 谁发的就定义在谁的 proto 里。客户端主动请求在
// gate/protos/gate.proto，game 推的在 game/protos/game.proto。三份文件之间
// **没有 import 关系**（各自的类型自包含）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: match/protos/match.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MatchResult 是匹配成功结果（match → 客户端 push route "onMatched"）。
type MatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId      string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                  // 对局 id
	GameServerId string `protobuf:"bytes,2,opt,name=game_server_id,json=gameServerId,proto3" json:"game_server_id,omitempty"` // 分配到的 game 节点 id
	PlayerIdx    int32  `protobuf:"varint,3,opt,name=player_idx,json=playerIdx,proto3" json:"player_idx,omitempty"`           // 本客户端在局内的玩家槽位（0/1）
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_protos_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_match_protos_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_match_protos_match_proto_rawDescGZIP(), []int{0}
}

func (x *MatchResult) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResult) GetGameServerId() string {
	if x != nil {
		return x.GameServerId
	}
	return ""
}

func (x *MatchResult) GetPlayerIdx() int32 {
	if x != nil {
		return x.PlayerIdx
	}
	return 0
}

// onMatchStatus 推送载荷：匹配期每秒一次。
type MatchStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueuedPlayers int32 `protobuf:"varint,1,opt,name=queued_players,json=queuedPlayers,proto3" json:"queued_players,omitempty"`
	WaitedSeconds int32 `protobuf:"varint,2,opt,name=waited_seconds,json=waitedSeconds,proto3" json:"waited_seconds,omitempty"`
}

func (x *MatchStatus) Reset() {
	*x = MatchStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_match_protos_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatus) ProtoMessage() {}

func (x *MatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_match_protos_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatus.ProtoReflect.Descriptor instead.
func (*MatchStatus) Descriptor() ([]byte, []int) {
	return file_match_protos_match_proto_rawDescGZIP(), []int{1}
}

func (x *MatchStatus) GetQueuedPlayers() int32 {
	if x != nil {
		return x.QueuedPlayers
	}
	return 0
}

func (x *MatchStatus) GetWaitedSeconds() int32 {
	if x != nil {
		return x.WaitedSeconds
	}
	return 0
}

var File_match_protos_match_proto protoreflect.FileDescriptor

var file_match_protos_match_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x6d, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x78,
	0x22, 0x5b, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x69, 0x74, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x77, 0x61, 0x69, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x15, 0x5a,
	0x13, 0x6a, 0x6f, 0x6c, 0x74, 0x67, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_match_protos_match_proto_rawDescOnce sync.Once
	file_match_protos_match_proto_rawDescData = file_match_protos_match_proto_rawDesc
)

func file_match_protos_match_proto_rawDescGZIP() []byte {
	file_match_protos_match_proto_rawDescOnce.Do(func() {
		file_match_protos_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_protos_match_proto_rawDescData)
	})
	return file_match_protos_match_proto_rawDescData
}

var file_match_protos_match_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_match_protos_match_proto_goTypes = []any{
	(*MatchResult)(nil), // 0: match.MatchResult
	(*MatchStatus)(nil), // 1: match.MatchStatus
}
var file_match_protos_match_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_match_protos_match_proto_init() }
func file_match_protos_match_proto_init() {
	if File_match_protos_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_match_protos_match_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_match_protos_match_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MatchStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_protos_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_protos_match_proto_goTypes,
		DependencyIndexes: file_match_protos_match_proto_depIdxs,
		MessageInfos:      file_match_protos_match_proto_msgTypes,
	}.Build()
	File_match_protos_match_proto = out.File
	file_match_protos_match_proto_rawDesc = nil
	file_match_protos_match_proto_goTypes = nil
	file_match_protos_match_proto_depIdxs = nil
}
