// Code generated by protoc-gen-redis. DO NOT EDIT.

package persistpb

import (
	"fmt"
	"github.com/gomodule/redigo/redis"
	"strconv"
)

// Enum DBSchemaVersion
type DBSchemaVersion int32

const (
	DBSchemaVersion_DB_SCHEMA_VERSION_UNSPECIFIED DBSchemaVersion = 0
	DBSchemaVersion_DB_SCHEMA_VERSION_CURRENT     DBSchemaVersion = 1
)

// --- protobuf wire format 辅助函数（语言无关序列化，规则见 https://protobuf.dev/programming-guides/encoding/） ---

// redisProtoAppendVarint 追加一个 base-128 varint 编码的 uint64
func redisProtoAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// redisProtoReadVarint 读取一个 varint，返回（值，消耗字节数）
func redisProtoReadVarint(b []byte) (uint64, int, error) {
	var v uint64
	for i := 0; i < len(b) && i < 10; i++ {
		v |= uint64(b[i]&0x7F) << (7 * i)
		if b[i]&0x80 == 0 {
			return v, i + 1, nil
		}
	}
	return 0, 0, fmt.Errorf("protobuf varint 读取失败: 数据截断或过长")
}

// redisProtoAppendTag 追加字段 tag（field<<3 | wireType）
func redisProtoAppendTag(buf []byte, field, wire int32) []byte {
	return redisProtoAppendVarint(buf, uint64(field)<<3|uint64(wire))
}

// redisProtoAppendLen 追加 length-delimited 数据（长度前缀 + 数据）
func redisProtoAppendLen(buf, payload []byte) []byte {
	buf = redisProtoAppendVarint(buf, uint64(len(payload)))
	return append(buf, payload...)
}

// redisProtoReadBytes 读取 length-delimited 数据，返回（数据拷贝，消耗字节数）；
// 返回拷贝避免与输入缓冲区 alias。
func redisProtoReadBytes(b []byte) ([]byte, int, error) {
	n, k, err := redisProtoReadVarint(b)
	if err != nil {
		return nil, 0, err
	}
	if n > uint64(len(b)-k) {
		return nil, 0, fmt.Errorf("protobuf length-delimited 数据截断: 期望 %d 字节, 剩余 %d", n, len(b)-k)
	}
	return append([]byte(nil), b[k:k+int(n)]...), k + int(n), nil
}

// redisProtoAppendFixed32 追加小端 4 字节
func redisProtoAppendFixed32(buf []byte, v uint32) []byte {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}

// redisProtoReadFixed32 读取小端 4 字节
func redisProtoReadFixed32(b []byte) (uint32, int, error) {
	if len(b) < 4 {
		return 0, 0, fmt.Errorf("protobuf fixed32 数据截断")
	}
	return uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24, 4, nil
}

// redisProtoAppendFixed64 追加小端 8 字节
func redisProtoAppendFixed64(buf []byte, v uint64) []byte {
	return append(buf,
		byte(v), byte(v>>8), byte(v>>16), byte(v>>24),
		byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}

// redisProtoReadFixed64 读取小端 8 字节
func redisProtoReadFixed64(b []byte) (uint64, int, error) {
	if len(b) < 8 {
		return 0, 0, fmt.Errorf("protobuf fixed64 数据截断")
	}
	var v uint64
	for i := 0; i < 8; i++ {
		v |= uint64(b[i]) << (8 * i)
	}
	return v, 8, nil
}

// redisProtoSkip 跳过未知字段，返回消耗字节数
func redisProtoSkip(b []byte, wire uint64) (int, error) {
	switch wire {
	case 0: // varint
		_, n, err := redisProtoReadVarint(b)
		return n, err
	case 1: // fixed64
		if len(b) < 8 {
			return 0, fmt.Errorf("protobuf fixed64 数据截断")
		}
		return 8, nil
	case 2: // length-delimited
		_, n, err := redisProtoReadBytes(b)
		return n, err
	case 5: // fixed32
		if len(b) < 4 {
			return 0, fmt.Errorf("protobuf fixed32 数据截断")
		}
		return 4, nil
	default:
		return 0, fmt.Errorf("protobuf 未知 wire type %d", wire)
	}
}

// --- Message: DBMetadata ---

// FieldDBMetadata 用于标识 Redis Hash 中的字段编号
type FieldDBMetadata uint32

// FieldDBMetadata_LastLoginAt 是字段 LastLoginAt 对应的 Redis Hash field 编号
const FieldDBMetadata_LastLoginAt FieldDBMetadata = 1

// FieldDBMetadataIDs 是所有字段编号常量的集合，类型为 []FieldDBMetadata
var FieldDBMetadataIDs = []FieldDBMetadata{
	FieldDBMetadata_LastLoginAt,
}

// DBMetadata 提供针对 DBMetadata 消息的 Redis 存取操作
type DBMetadata struct {
	LastLoginAt int64
}

// NewDBMetadata 创建一个新的 DBMetadata 实例
func NewDBMetadata() *DBMetadata {
	return &DBMetadata{}
}

// MarshalRedisProto 将 DBMetadata 序列化为 protobuf wire format 字节流。
// 字节流与语言无关：任何语言使用同一份 .proto 定义即可解析。
// 编码遵循 proto3 语义：零值标量/空字符串/空 bytes 不编码，message 字段恒编码，
// repeated 逐元素编码（含零值），map 每键值对编码为子消息（field 1=key, field 2=value）。
func (p *DBMetadata) MarshalRedisProto() ([]byte, error) {
	var buf []byte

	// 字段 LastLoginAt（tag 1）

	// 枚举与整型（varint）
	if p.LastLoginAt != 0 {
		buf = redisProtoAppendTag(buf, 1, 0)
		buf = redisProtoAppendVarint(buf, uint64(p.LastLoginAt))
	}

	return buf, nil
}

// UnmarshalRedisProto 从 protobuf wire format 字节流反序列化到 DBMetadata。
// 反序列化前会先重置自身；未知字段跳过，缺失字段保持零值（proto3 语义）。
func (p *DBMetadata) UnmarshalRedisProto(b []byte) error {
	*p = DBMetadata{}
	for len(b) > 0 {
		tag, n, err := redisProtoReadVarint(b)
		if err != nil {
			return fmt.Errorf("protobuf 读取字段 tag 失败: %v", err)
		}
		b = b[n:]
		field := tag >> 3
		wire := tag & 7
		switch field {

		case 1: // LastLoginAt

			// 枚举与整型（varint）
			if wire != 0 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "LastLoginAt", wire)
			}
			v, n, err := redisProtoReadVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			p.LastLoginAt = int64(v)

		default:
			n, err = redisProtoSkip(b, wire)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

// GetFields 从 Redis Hash 中读取指定字段的值，填充到当前结构体实例中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要读取的字段编号列表，如 FieldDBMetadata_Name, FieldDBMetadata_Age
//
//	如果 fields 为空（长度为 0），则默认读取所有字段（即 FieldDBMetadataIDs）
//	集合字段（map/repeated）整体 protobuf 反序列化
func (p *DBMetadata) GetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...FieldDBMetadata) error {
	key := fmt.Sprintf("acct:%d:%d:%d", REDBKey, ida, idb)

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = FieldDBMetadataIDs
	}

	// 构造 HMGET 参数：key + fieldID1 + fieldID2 + ...，一次取回全部字段值
	args := []interface{}{key}
	for _, fieldID := range fieldsToUse {
		args = append(args, fieldID)
	}

	// 一次 HMGET 获取所有字段值
	reply, err := conn.Do("HMGET", args...)
	if err != nil {
		return fmt.Errorf("HMGET 失败: %v", err)
	}

	// 解析返回的 []interface{} 列表
	values, err := redis.Values(reply, nil)
	if err != nil {
		return fmt.Errorf("解析 HMGET 结果失败: %v", err)
	}

	// 逐一处理每个字段
	fieldIndex := 0
	for _, fieldID := range fieldsToUse {
		switch fieldID {

		case FieldDBMetadata_LastLoginAt:

			// --- 直读字段: LastLoginAt ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {

				id, err := strconv.ParseInt(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "LastLoginAt", err)
				}
				p.LastLoginAt = id

			}

		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
		fieldIndex++
	}

	return nil
}

// SetFields 将当前结构体实例的字段值，存储到 Redis Hash 中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要存储的字段编号列表，如 FieldDBMetadata_Name, FieldDBMetadata_Age
//
//	如果 fields 为空（长度为 0），则默认存储所有字段（即 FieldDBMetadataIDs）
//	集合字段（map/repeated）整体 protobuf 序列化后写入
func (p *DBMetadata) SetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...FieldDBMetadata) error {
	key := fmt.Sprintf("acct:%d:%d:%d", REDBKey, ida, idb)
	args := []interface{}{key}

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = FieldDBMetadataIDs
	}

	for _, fieldID := range fieldsToUse {
		switch fieldID {

		case FieldDBMetadata_LastLoginAt:

			// --- 直存字段: LastLoginAt ---
			args = append(args, fieldID, p.LastLoginAt)

		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
	}

	// 所有字段统一一次 HSET 写入
	if len(args) > 1 {
		_, err := conn.Do("HSET", args...)
		return err
	}
	return nil
}

// ---------- 字段级 protobuf 编码/解码模板块（MarshalRedisProto / UnmarshalRedisProto
// 与集合字段的字段级序列化方法共用） ----------
//
// 约定上下文变量：fieldEncode 向 buf 追加字节；fieldDecode 从 b 消费一个字段段，
// 校验 wire 变量，解码结果写入 p.<Name>。

// --- Message: DBAccount ---

// FieldDBAccount 用于标识 Redis Hash 中的字段编号
type FieldDBAccount uint32

// FieldDBAccount_Username 是字段 Username 对应的 Redis Hash field 编号
const FieldDBAccount_Username FieldDBAccount = 1

// FieldDBAccount_PassHash 是字段 PassHash 对应的 Redis Hash field 编号
const FieldDBAccount_PassHash FieldDBAccount = 2

// FieldDBAccount_CreatedAt 是字段 CreatedAt 对应的 Redis Hash field 编号
const FieldDBAccount_CreatedAt FieldDBAccount = 3

// FieldDBAccount_SchemaVersion 是字段 SchemaVersion 对应的 Redis Hash field 编号
const FieldDBAccount_SchemaVersion FieldDBAccount = 4

// FieldDBAccount_Metadata 是字段 Metadata 对应的 Redis Hash field 编号
const FieldDBAccount_Metadata FieldDBAccount = 5

// FieldDBAccountIDs 是所有字段编号常量的集合，类型为 []FieldDBAccount
var FieldDBAccountIDs = []FieldDBAccount{
	FieldDBAccount_Username,
	FieldDBAccount_PassHash,
	FieldDBAccount_CreatedAt,
	FieldDBAccount_SchemaVersion,
	FieldDBAccount_Metadata,
}

// DBAccount 提供针对 DBAccount 消息的 Redis 存取操作
type DBAccount struct {
	Username string

	PassHash string

	CreatedAt int64

	SchemaVersion DBSchemaVersion

	Metadata DBMetadata
}

// NewDBAccount 创建一个新的 DBAccount 实例
func NewDBAccount() *DBAccount {
	return &DBAccount{}
}

// MarshalRedisProto 将 DBAccount 序列化为 protobuf wire format 字节流。
// 字节流与语言无关：任何语言使用同一份 .proto 定义即可解析。
// 编码遵循 proto3 语义：零值标量/空字符串/空 bytes 不编码，message 字段恒编码，
// repeated 逐元素编码（含零值），map 每键值对编码为子消息（field 1=key, field 2=value）。
func (p *DBAccount) MarshalRedisProto() ([]byte, error) {
	var buf []byte

	// 字段 Username（tag 1）

	if p.Username != "" {
		buf = redisProtoAppendTag(buf, 1, 2)
		buf = redisProtoAppendLen(buf, []byte(p.Username))
	}

	// 字段 PassHash（tag 2）

	if p.PassHash != "" {
		buf = redisProtoAppendTag(buf, 2, 2)
		buf = redisProtoAppendLen(buf, []byte(p.PassHash))
	}

	// 字段 CreatedAt（tag 3）

	// 枚举与整型（varint）
	if p.CreatedAt != 0 {
		buf = redisProtoAppendTag(buf, 3, 0)
		buf = redisProtoAppendVarint(buf, uint64(p.CreatedAt))
	}

	// 字段 SchemaVersion（tag 4）

	// 枚举与整型（varint）
	if p.SchemaVersion != 0 {
		buf = redisProtoAppendTag(buf, 4, 0)
		buf = redisProtoAppendVarint(buf, uint64(p.SchemaVersion))
	}

	// 字段 Metadata（tag 5）

	{
		b, err := p.Metadata.MarshalRedisProto()
		if err != nil {
			return nil, fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "Metadata", err)
		}
		buf = redisProtoAppendTag(buf, 5, 2)
		buf = redisProtoAppendLen(buf, b)
	}

	return buf, nil
}

// UnmarshalRedisProto 从 protobuf wire format 字节流反序列化到 DBAccount。
// 反序列化前会先重置自身；未知字段跳过，缺失字段保持零值（proto3 语义）。
func (p *DBAccount) UnmarshalRedisProto(b []byte) error {
	*p = DBAccount{}
	for len(b) > 0 {
		tag, n, err := redisProtoReadVarint(b)
		if err != nil {
			return fmt.Errorf("protobuf 读取字段 tag 失败: %v", err)
		}
		b = b[n:]
		field := tag >> 3
		wire := tag & 7
		switch field {

		case 1: // Username

			if wire != 2 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "Username", wire)
			}
			v, n, err := redisProtoReadBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			p.Username = string(v)

		case 2: // PassHash

			if wire != 2 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "PassHash", wire)
			}
			v, n, err := redisProtoReadBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			p.PassHash = string(v)

		case 3: // CreatedAt

			// 枚举与整型（varint）
			if wire != 0 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "CreatedAt", wire)
			}
			v, n, err := redisProtoReadVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			p.CreatedAt = int64(v)

		case 4: // SchemaVersion

			// 枚举与整型（varint）
			if wire != 0 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "SchemaVersion", wire)
			}
			v, n, err := redisProtoReadVarint(b)
			if err != nil {
				return err
			}
			b = b[n:]
			p.SchemaVersion = DBSchemaVersion(v)

		case 5: // Metadata

			if wire != 2 {
				return fmt.Errorf("protobuf 字段 %s wire type 错误: %d", "Metadata", wire)
			}
			v, n, err := redisProtoReadBytes(b)
			if err != nil {
				return err
			}
			b = b[n:]
			if err := p.Metadata.UnmarshalRedisProto(v); err != nil {
				return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "Metadata", err)
			}

		default:
			n, err = redisProtoSkip(b, wire)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

// GetFields 从 Redis Hash 中读取指定字段的值，填充到当前结构体实例中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要读取的字段编号列表，如 FieldDBAccount_Name, FieldDBAccount_Age
//
//	如果 fields 为空（长度为 0），则默认读取所有字段（即 FieldDBAccountIDs）
//	集合字段（map/repeated）整体 protobuf 反序列化
func (p *DBAccount) GetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...FieldDBAccount) error {
	key := fmt.Sprintf("acct:%d:%d:%d", REDBKey, ida, idb)

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = FieldDBAccountIDs
	}

	// 构造 HMGET 参数：key + fieldID1 + fieldID2 + ...，一次取回全部字段值
	args := []interface{}{key}
	for _, fieldID := range fieldsToUse {
		args = append(args, fieldID)
	}

	// 一次 HMGET 获取所有字段值
	reply, err := conn.Do("HMGET", args...)
	if err != nil {
		return fmt.Errorf("HMGET 失败: %v", err)
	}

	// 解析返回的 []interface{} 列表
	values, err := redis.Values(reply, nil)
	if err != nil {
		return fmt.Errorf("解析 HMGET 结果失败: %v", err)
	}

	// 逐一处理每个字段
	fieldIndex := 0
	for _, fieldID := range fieldsToUse {
		switch fieldID {

		case FieldDBAccount_Username:

			// --- 直读字段: Username ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {

				p.Username = string(val)

			}

		case FieldDBAccount_PassHash:

			// --- 直读字段: PassHash ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {

				p.PassHash = string(val)

			}

		case FieldDBAccount_CreatedAt:

			// --- 直读字段: CreatedAt ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {

				id, err := strconv.ParseInt(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析字段 %s 失败: %v", "CreatedAt", err)
				}
				p.CreatedAt = id

			}

		case FieldDBAccount_SchemaVersion:

			// --- 直读字段: SchemaVersion ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {

				intValue, err := strconv.ParseInt(string(val), 10, 64)
				if err != nil {
					return fmt.Errorf("解析枚举字段 %s 失败: %v", "SchemaVersion", err)
				}
				p.SchemaVersion = DBSchemaVersion(int32(intValue))

			}

		case FieldDBAccount_Metadata:

			// --- Protobuf 反序列化字段: Metadata ---
			if val, ok := values[fieldIndex].([]byte); ok && val != nil {
				if err := p.Metadata.UnmarshalRedisProto(val); err != nil {
					return fmt.Errorf("protobuf 反序列化字段 %s 失败: %v", "Metadata", err)
				}
			}

		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
		fieldIndex++
	}

	return nil
}

// SetFields 将当前结构体实例的字段值，存储到 Redis Hash 中
// conn: Redis 连接
// REDBKey: 业务维度 Key
// ida, idb: 用于组成唯一 Hash Key 的两个 uint64 分片维度
// fields: 要存储的字段编号列表，如 FieldDBAccount_Name, FieldDBAccount_Age
//
//	如果 fields 为空（长度为 0），则默认存储所有字段（即 FieldDBAccountIDs）
//	集合字段（map/repeated）整体 protobuf 序列化后写入
func (p *DBAccount) SetFields(conn redis.Conn, REDBKey uint32, ida, idb uint64, fields ...FieldDBAccount) error {
	key := fmt.Sprintf("acct:%d:%d:%d", REDBKey, ida, idb)
	args := []interface{}{key}

	// 决定要操作的字段列表
	fieldsToUse := fields
	if len(fieldsToUse) == 0 {
		fieldsToUse = FieldDBAccountIDs
	}

	for _, fieldID := range fieldsToUse {
		switch fieldID {

		case FieldDBAccount_Username:

			// --- 直存字段: Username ---
			args = append(args, fieldID, p.Username)

		case FieldDBAccount_PassHash:

			// --- 直存字段: PassHash ---
			args = append(args, fieldID, p.PassHash)

		case FieldDBAccount_CreatedAt:

			// --- 直存字段: CreatedAt ---
			args = append(args, fieldID, p.CreatedAt)

		case FieldDBAccount_SchemaVersion:

			// --- 直存字段: SchemaVersion ---
			args = append(args, fieldID, p.SchemaVersion)

		case FieldDBAccount_Metadata:

			// --- Protobuf 序列化字段: Metadata ---
			{
				b, err := p.Metadata.MarshalRedisProto()
				if err != nil {
					return fmt.Errorf("protobuf 序列化字段 %s 失败: %v", "Metadata", err)
				}
				args = append(args, fieldID, b)
			}

		default:
			return fmt.Errorf("未知字段编号: %d", fieldID)
		}
	}

	// 所有字段统一一次 HSET 写入
	if len(args) > 1 {
		_, err := conn.Do("HSET", args...)
		return err
	}
	return nil
}

// ---------- 字段级 protobuf 编码/解码模板块（MarshalRedisProto / UnmarshalRedisProto
// 与集合字段的字段级序列化方法共用） ----------
//
// 约定上下文变量：fieldEncode 向 buf 追加字节；fieldDecode 从 b 消费一个字段段，
// 校验 wire 变量，解码结果写入 p.<Name>。
